"""The RSA live campaign's launcher config: check it, show its cost, render Prolific's settings.

    uv run python -m src.rsa.live.config --config scripts/rsa/live/rsa_live.yaml --check
    uv run python -m src.rsa.live.config --config scripts/rsa/live/rsa_live.yaml --render   # into this checkout

``--check`` validates the config and prints what a launch would recruit and
cost (Prolific's reward plus its service fee, main's estimate). ``--render``
writes the ``prolific:`` block to the RSA project's ``prolific_config.yaml``
(gitignored; main's deployment reads it), without a participant count: the
count reaches the pipeline once, as ``--participants``.
"""

from __future__ import annotations

import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import List

import tyro
import yaml

from src.pipelines.outer_loop.deployment.prolific import build_eligibility_filters, compute_reward_cents
from src.rsa.live.collect import PROJECT_ID
from src.runtime.prolific import prolific_config_path

PROLIFIC_SERVICE_FEE = 0.33  # main's estimate (scripts/outer_loop_live/_pilot_config.py); check the account's rate
REQUIRED = ("firebase_project", "series_label", "chains", "experiments", "participants", "displays", "prolific")


@dataclass
class Args:
    config: Path
    check: bool = False
    render: bool = False


def load(path: Path) -> dict:
    cfg = yaml.safe_load(Path(path).read_text())
    missing = [k for k in REQUIRED if k not in cfg]
    if missing:
        raise ValueError(f"{path} lacks {missing}")
    if "participants" in cfg["prolific"] or "total_available_places" in cfg["prolific"]:
        raise ValueError("the participant count is the top-level `participants`, not a prolific: key")
    if not isinstance(cfg.get("confirm_live_recruitment", False), bool):
        raise ValueError("confirm_live_recruitment must be true or false")
    for k in cfg["chains"]:
        site = hosting_site(cfg, k)
        if len(site) > 30 or not re.fullmatch(r"[a-z0-9-]+", site):
            raise ValueError(f"Hosting site id {site!r} must be <= 30 characters of [a-z0-9-]")
    build_eligibility_filters(cfg["prolific"])  # raises on a bad approval rate
    return cfg


def hosting_site(cfg: dict, chain: int) -> str:
    return f"{cfg['firebase_project']}-{cfg['series_label']}-c{chain}"


def cost(cfg: dict) -> dict:
    reward = compute_reward_cents(cfg["prolific"])
    per_study = reward * cfg["participants"]
    per_study_total = per_study + round(per_study * PROLIFIC_SERVICE_FEE)
    studies = len(cfg["chains"]) * cfg["experiments"]
    return dict(reward_cents=reward, per_study_cents=per_study_total, studies=studies,
                participants=studies * cfg["participants"], total_cents=per_study_total * studies)


def render(cfg: dict) -> Path:
    path = prolific_config_path(PROJECT_ID)
    if not path.parent.is_dir():
        raise FileNotFoundError(f"no project directory {path.parent}")
    header = "# AUTO-GENERATED by `python -m src.rsa.live.config --render` from the RSA live config. Do not edit.\n\n"
    path.write_text(header + yaml.safe_dump(cfg["prolific"], sort_keys=False, allow_unicode=True), encoding="utf-8")
    return path


def summary(cfg: dict) -> List[str]:
    c = cost(cfg)
    return [
        f"study name     : {cfg['prolific']['name']}",
        f"chains         : {cfg['chains']}  (sites {', '.join(hosting_site(cfg, k) for k in cfg['chains'])})",
        f"per experiment : {cfg['participants']} people x {cfg['prolific']['estimated_completion_time']} min, "
        f"reward ${c['reward_cents'] / 100:.2f} each; ${c['per_study_cents'] / 100:,.2f} with the fee",
        f"campaign       : {c['studies']} studies, {c['participants']} people, ~${c['total_cents'] / 100:,.2f}",
        f"confirmed      : {cfg.get('confirm_live_recruitment', False)}",
    ]


def main(args: Args) -> None:
    cfg = load(args.config)
    if args.check:
        print("\n".join(summary(cfg)), file=sys.stderr)
    if args.render:
        print(f"[render] wrote {render(cfg)}", file=sys.stderr)


if __name__ == "__main__":
    main(tyro.cli(Args))
