"""Validation for 2_design outputs."""

from pathlib import Path
from typing import Any, Dict

from src.validation.types import Validated


def validate_designer_output(run_dir: Path) -> Validated:
    run_dir = Path(run_dir)
    path = run_dir / "2_design" / "stimuli.json"
    details: Dict[str, Any] = {}

    if not path.exists():
        return Validated(False, "stimuli.json not found", {"path": str(path)})

    try:
        data = __import__("json").loads(path.read_text(encoding="utf-8"))
    except Exception as exc:
        return Validated(False, f"Invalid JSON: {exc}", {"path": str(path)})

    if not isinstance(data, list):
        return Validated(False, "stimuli.json is not a list", details)

    eig_values = []
    for i, item in enumerate(data):
        if not isinstance(item, dict):
            return Validated(False, f"Stimulus {i} is not a dict", {"index": i})
        if "sequence_a" not in item or "sequence_b" not in item:
            return Validated(
                False, f"Stimulus {i} missing sequence_a or sequence_b", {"index": i}
            )
        if "eig" not in item:
            return Validated(
                False,
                f"Stimulus {i} missing required 'eig' field (EIG value for observability)",
                {"index": i},
            )
        try:
            eig_values.append(float(item["eig"]))
        except (TypeError, ValueError):
            return Validated(False, f"Stimulus {i} has non-numeric 'eig'", {"index": i})

    details["n_stimuli"] = len(data)
    if not eig_values:
        return Validated(
            True, f"Designer output valid; {len(data)} stimuli (no eig)", details
        )
    details["eig_min"] = min(eig_values)
    details["eig_max"] = max(eig_values)
    if max(eig_values) <= 0:
        return Validated(
            False,
            "All EIG values are <= 0; check design script (stimulus must be tuple for get_model_predictions)",
            details,
        )

    rationale_path = run_dir / "2_design" / "design_rationale.md"
    if rationale_path.exists():
        rationale_preview = rationale_path.read_text(encoding="utf-8").strip()[:200]
        if rationale_preview.startswith("Fallback design:"):
            return Validated(
                False,
                "Design was generated by the fallback (no LLM script was used or script failed). "
                "You must output exactly one fenced ```python block containing the full design script. "
                "Do not implement EIG yourself; call expected_information_gain((seq_a, seq_b)). "
                "Each stimulus in stimuli.json must include an 'eig' field.",
                {**details, "fallback_used": True},
            )
    return Validated(
        True,
        f"Designer output valid; {len(data)} stimuli, EIG range [{min(eig_values):.4f}, {max(eig_values):.4f}]",
        details,
    )
