"""The novelty gate's context pool and prediction distance for memo models.

A candidate is novel when its posterior-mean choice probabilities differ from
every admitted model's by at least a threshold (RMSE over the pool). The pool
is generated by the loop, deliberately not the training displays (the PyMC
domain learned that models distinct in mechanism can agree on the training
stimuli): every game up to 4 objects x 4 features with each word and a prior
query, plus copies of the 3-object games under each manipulation the data
contain (valence, a familiarization base rate favouring one object, one
object in grayscale), so a model that reads a manipulation can differ there.

Probabilities are compared per choice class (identical objects summed), the
unit the likelihood observes.
"""

from __future__ import annotations

import hashlib
import json
from typing import Dict, List, Mapping, Sequence

import numpy as np

from src.rsa.context import Context, group_by_shape
from src.rsa.design_space import context_pool, games
from src.rsa.fit import RSAFit, class_probs
from src.rsa.model_file import RSAModel

DEFAULT_NOVELTY_RMSE_THRESHOLD = 0.002
POOL_SIZES = ((2, 2), (3, 2), (3, 3), (3, 4), (4, 2), (4, 3), (4, 4))
MAX_DRAWS = 100


def novelty_pool() -> List[Context]:
    pool = context_pool(POOL_SIZES, include_prior_queries=True)
    for n_feat in (2, 3):
        names = tuple(f"f{i}" for i in range(n_feat))
        for matrix in games(3, n_feat):
            for word in [None, *range(n_feat)]:
                for valence in (-1, 1):
                    pool.append(Context(objects=matrix, feature_names=names, utterance=word, valence=valence))
                for favoured in range(3):
                    fam = tuple(7 / 9 if i == favoured else 1 / 9 for i in range(3))
                    pool.append(Context(objects=matrix, feature_names=names, utterance=word, familiarization=fam))
                for gray in range(3):
                    mask = tuple(int(i != gray) for i in range(3))  # one object in colour
                    pool.append(Context(objects=matrix, feature_names=names, utterance=word, grayscale=mask))
    return pool


def pool_digest(pool: Sequence[Context]) -> str:
    blob = json.dumps([pool_record(c) for c in pool], sort_keys=True).encode()
    return hashlib.sha256(blob).hexdigest()[:16]


def pool_record(ctx: Context) -> dict:
    return dict(
        objects=ctx.objects, utterance=ctx.utterance, valence=ctx.valence,
        familiarization=ctx.familiarization, grayscale=ctx.grayscale,
    )


def posterior_mean_class_probs(
    model: RSAModel, fitted: RSAFit, pool: Sequence[Context], max_draws: int = MAX_DRAWS
) -> np.ndarray:
    """Posterior-mean choice-class probabilities over the pool, flattened.

    Raises ValueError when the model's probabilities are not finite on some
    pool context (a model failure: the caller rejects with the reason).
    """
    post = fitted.idata.posterior
    flat = {k: np.asarray(post[k]).reshape(-1) for k in fitted.param_names}
    n = len(next(iter(flat.values())))
    take = np.linspace(0, n - 1, min(max_draws, n)).astype(int)
    out: Dict[int, np.ndarray] = {}
    for group in group_by_shape(pool).values():
        acc = 0.0
        for i in take:
            p = model.group_probs({k: v[i] for k, v in flat.items()}, group)
            acc = acc + np.asarray(class_probs(p, group.classes))
        mean = acc / len(take)
        if not np.all(np.isfinite(mean)):
            bad = [pool[group.indices[r]] for r in np.where(~np.isfinite(mean).all(axis=1))[0][:3]]
            raise ValueError(
                f"{model.name}'s choice probabilities are not finite on pool contexts such as "
                + "; ".join(json.dumps(pool_record(c)) for c in bad)
            )
        for row, idx in enumerate(group.indices):
            out[int(idx)] = mean[row]
    return np.concatenate([out[i] for i in range(len(pool))])


def closest(candidate: np.ndarray, admitted: Mapping[str, np.ndarray]) -> tuple[str, float]:
    """The admitted model whose pool predictions are nearest (RMSE), and the distance."""
    if not admitted:
        return "", float("inf")
    dists = {name: float(np.sqrt(np.mean((candidate - v) ** 2))) for name, v in admitted.items()}
    name = min(dists, key=dists.get)
    return name, dists[name]
