"""
People judge a sequence as less random when it contains detectable periodic structure — a
regular repeating pattern is the strongest cue that the sequence was generated by a rule
rather than chance. When comparing two sequences, people prefer the one with lower
periodicity as the more random-looking option.
"""

import numpy as np
import pymc as pm
import pytensor.tensor as pt

with pm.Model() as model:
    periodicity_a = pm.Data("periodicity_a", np.zeros(1, dtype="float64"))
    periodicity_b = pm.Data("periodicity_b", np.zeros(1, dtype="float64"))

    # Sensitivity to periodic structure: higher tau → stronger periodicity avoidance
    tau = pm.HalfNormal("tau", sigma=2.0)

    # Higher periodicity → less random; prefer whichever sequence is less periodic
    p_left = pm.Deterministic(
        "p_left", pm.math.sigmoid(tau * (periodicity_b - periodicity_a))
    )

    chose_left = pm.Data("chose_left", np.zeros(1, dtype="int64"))
    pm.Bernoulli("response", p=p_left, observed=chose_left)
