# file: griffiths_tenenbaum_2001.py
import numpy as np
import pymc as pm
import pytensor.tensor as pt

with pm.Model() as model:
    # Stimulus features for sequence A
    n_a = pm.Data("n_a", np.zeros(1, dtype="int64"))
    h_a = pm.Data("h_a", np.zeros(1, dtype="int64"))
    alts_a = pm.Data("alts_a", np.zeros(1, dtype="int64"))

    # Stimulus features for sequence B
    n_b = pm.Data("n_b", np.zeros(1, dtype="int64"))
    h_b = pm.Data("h_b", np.zeros(1, dtype="int64"))
    alts_b = pm.Data("alts_b", np.zeros(1, dtype="int64"))

    # Free parameter: softmax temperature
    tau = pm.HalfNormal("tau", sigma=10.0)

    def logp_rand(n):
        """Log-likelihood of the sequence under a fair coin (p=0.5)."""
        return n * pt.log(0.5)

    def logp_reg_bias(n, h):
        """Marginal log-likelihood under a biased coin with Uniform(0,1) prior on p."""
        return pt.gammaln(h + 1.0) + pt.gammaln(n - h + 1.0) - pt.gammaln(n + 2.0)

    def logp_reg_alt(n, alts):
        """Marginal log-likelihood under a Markov model with Uniform(0,1) prior on alternation probability."""
        return (
            pt.log(0.5)
            + pt.gammaln(alts + 1.0)
            + pt.gammaln(n - alts)
            - pt.gammaln(n + 1.0)
        )

    def logp_reg(n, h, alts):
        """Log-likelihood under the regular model (50/50 mixture of bias and alternation)."""
        lp_bias = logp_reg_bias(n, h)
        lp_alt = logp_reg_alt(n, alts)
        return pt.log(0.5) + pm.math.logaddexp(lp_bias, lp_alt)

    # Cast to float64 for continuous math operations (gammaln)
    n_a_f = pt.cast(n_a, "float64")
    h_a_f = pt.cast(h_a, "float64")
    alts_a_f = pt.cast(alts_a, "float64")

    n_b_f = pt.cast(n_b, "float64")
    h_b_f = pt.cast(h_b, "float64")
    alts_b_f = pt.cast(alts_b, "float64")

    # Log-likelihood ratio (LLR) of random vs. regular model
    # Higher LLR means the sequence is more likely to be generated by the random model
    llr_a = logp_rand(n_a_f) - logp_reg(n_a_f, h_a_f, alts_a_f)
    llr_b = logp_rand(n_b_f) - logp_reg(n_b_f, h_b_f, alts_b_f)

    # Probability of choosing sequence A (left)
    p_left = pm.Deterministic("p_left", pm.math.sigmoid(tau * (llr_a - llr_b)))

    # Observed responses
    chose_left = pm.Data("chose_left", np.zeros(1, dtype="int64"))
    pm.Bernoulli("response", p=p_left, observed=chose_left)
